### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by tobias-kirschstein** [blobfile/blobfile#227]
With Python 3.8 on a Windows machine I receive the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Programs\Programming\miniconda\envs\diffusionrig\lib\site-packages\blobfile\__init__.py", line 6, in <module>
    from blobfile._ops import (
  File "C:\Programs\Programming\miniconda\envs\diffusionrig\lib\site-packages\blobfile\_ops.py", line 19, in <module>
    from blobfile._common import DirEntry, Stat, RemoteOrLocalPath
  File "C:\Programs\Programming\miniconda\envs\diffusionrig\lib\site-packages\blobfile\_common.py", line 1025, in <module>
    RemoteOrLocalPath = Union[str, BlobPathLike, os.PathLike[str]]
TypeError: 'ABCMeta' object is not subscriptable
```

Steps to reproduce:
```
conda create -n blobfile-test python==3.8
conda activate blobfile-test
pip install blobfile
python -c "import blobfile"
```

What am I doing wrong?

**Comment by GritYu** [comment]
I have the same issue! Please let me if you have solution! Thank you!

**Comment by hauntsaninja** [comment]
Thanks for the report! I'll cut a new release with the fix soon

**Comment by tobias-kirschstein** [comment]
Oh wow that was lightning fast. Thanks!

**Comment by GritYu** [comment]
That's awesome!

**Comment by hauntsaninja** [comment]
This is released in blobfile 2.1.1 https://pypi.org/project/blobfile/#history
Let me know if you're still having issues!

**Comment by curtain-call** [comment]
Still have the problem while using version 2.1.1. Please give me a hand.

**Comment by hauntsaninja** [comment]
What is your repro? You'll need to provide more information to get effective help. E.g. the following works for me:
```
python3.8 -m pip install blobfile==2.1.1
python3.8 -c 'import blobfile'
python3.8 -c 'import blobfile; print(blobfile.BlobFile("https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken").read())'
```

**Comment by curtain-call** [comment]
sorry! the problem I've met is that when I use 
    pip install blobfile==2.1.1
I still suffer from the problem " 'ABCMeta' object is not subscriptable". Also, I download the package an install by hand cannot solve the problem.
so I have to modify the _common.py file manually, I change the 
    RemoteOrLocalPath = Union[str, BlobPathLike, os.PathLike[str]]  
to 
    RemoteOrLocalPath = Union[str, BlobPathLike, "os.PathLike[str]"] 
then it works.
thank you for your concern! Expecting to have a off-the-shelf pip package soon!




Best wishes!
















At 2023-11-05 13:08:36, "Shantanu" ***@***.***> wrote:

What is your repro? You'll need to provide more information to get effective help. E.g. the following works for me:

python3.8 -m pip install blobfile==2.1.1
python3.8 -c 'import blobfile'
python3.8 -c 'import blobfile; print(blobfile.BlobFile("https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken").read())'
